#!/bin/bash

# RUN translate_env to fix environemt variables
pushd config/ > /dev/null || exit
./translate_env.sh
popd > /dev/null || exit 

# Set environment variables for the container runtime
USER_UID=${UID}
USER_GID=${GID}

if command -v podman &> /dev/null; then
    USER_UID=${USER_UID} USER_GID=${USER_GID} podman compose up -d
elif command -v docker &> /dev/null; then
    USER_UID=${USER_UID} USER_GID=${USER_GID} docker compose up -d
else
    echo "A known container runtime is not available"
fi
