---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
  - Github:
    - abbr:
      href: https://github.com/
      icon: github.png
  - Gitlab:
    - abbr:
      href: https://gitlab.com/
      icon: gitlab.png
  - ChatGPT:
    - abbr:
      href: https://chatgpt.com/
      icon: chatgpt.png
  - Stackoverflow:
    - abbr:
      href: https://stackoverflow.com/
      icon: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Stack_Overflow_icon.svg/2048px-Stack_Overflow_icon.svg.png
  - Homepage-icons:
    - abbr:
      href: https://github.com/walkxcode/dashboard-icons/tree/main/png
      icon: homepage.png
  - Homepage-server:
    - abbr:
      href: http://desk-truenas.duckdns.org:30054/
      icon: homepage.png

- Entertainment:
  - YouTube:
    - abbr:
      href: https://youtube.com/
      icon: youtube.png
  - Netflix:
    - abbr:
      href: https://netflix.com
      icon: netflix.png
  - Y-Music:
    - abbr:
      href: https://music.youtube.com/
      icon: youtube-music.png
  - Spotify:
    - abbr:
      href: https://open.spotify.com
      icon: spotify.png
  - Skroutz:
    - abbr:
      href: https://www.skroutz.gr/
      icon: https://play-lh.googleusercontent.com/NINIMeezs4kFXbmKMoW3L2GYqC_kwBgho98V-t4Mr_PVQKCtXagrt04QIf26p192HOOE
  - E-Food:
    - abbr:
      href: https://www.e-food.gr/
      icon: https://play-lh.googleusercontent.com/AL3O4ziZLPk7DCBtKvwosWefQmDedPvR3VT3kMXo07hdAY70lqoIXa6Q_q3CnO_o7GU
  - Amazon.de:
    - abbr:
      href: https://amazon.de/
      icon: https://files.softicons.com/download/social-media-icons/simple-icons-by-dan-leech/png/256x256/amazon.png

- Social:
  - LinkedIn:
    - abbr:
      href: https://www.linkedin.com/
      icon: linkedin.png
  - Facebook:
    - abbr:
      href: https://www.facebook.com/
      icon: facebook.png
  - Messenger:
    - abbr: 
      href: https://www.messenger.com
      icon: facebook-messenger.png
  - Instagram:
    - abbr:
      href: https://www.instagram.com/
      icon: instagram.png
  - X:
    - abbr:
      href: https://x.com/
      icon: x.png
  - Reddit:
    - abbr:
      href: https://reddit.com/
      icon: reddit.png

- Google:
  - GMAIL:
    - abbr:
      href: https://mail.google.com
      icon: gmail.png
  - Driver:
    - abbr:
      href: https://drive.google.com/
      icon: google-drive.png
  - Calendar:
    - abbr:
      href: https://calendar.google.com/
      icon: google-calendar.png
  - Meet: 
    - abbr:
      href: https://meet.google.com
      icon: google-meet.png
  - Chat: 
    - abbr:
      href: https://chat.google.com
      icon: google-chat.png
  - Maps:
    - abbr:
      href: https://www.google.com/maps
      icon: google-maps.png

- Work: 
  - Paypal:
    - abbr:
      href: https://www.paypal.com/
      icon: https://cdn-icons-png.flaticon.com/512/2504/2504802.png
  - Monday:
    - abbr: 
      href: https://monday.com
      icon: https://marketing.wearedrew.co/hubfs/logomonday.com_.png?width=500&height=auto&name=image.png
  - DuckDNS:
    - abbr:
      href: https://www.duckdns.org/
      icon: https://c10.patreonusercontent.com/4/patreon-media/p/campaign/351251/f88f5d4bc3434344b925b9d62e4dcd49/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/1.png?token-time=1735948800&token-hash=hU5K48eoCUot7Od0iH4J1vHDqlYfXMt5IOTlIKP-IqI%3D
  - NameCheap:
    - abbr:
      href: https://www.namecheap.com/
      icon: https://static-00.iconduck.com/assets.00/namecheap-icon-2048x2048-ft2h6a21.png
  - Udemy:
    - abbr:
      href: https://www.udemy.com
      icon: udemy.png
  - Proxmox helper scripts:
    - abbr: 
      href: https://community-scripts.github.io/ProxmoxVE/scripts
      icon: https://community-scripts.github.io/ProxmoxVE/logo.png
      
- Travelling:
  - Booking:
    - abbr:
      href: https://www.booking.com/
      icon: https://cdn.bookingexperts.nl/uploads/app_store_application/logo/22/Booking.com.png
  - Airbnb:
    - abbr: 
      href: https://www.airbnb.com
      icon: https://avatars.githubusercontent.com/u/698437?s=200&v=4
  - Skyscanner:
    - abbr:
      href: https://www.skyscanner.com
      icon: https://play-lh.googleusercontent.com/pwbvaHWLNzOuqF71hu2P36HV1Yi2lkwwRCNT0QChysbrSucDulfBNxLBMZKQgsZUfyU=s256-rw
  - Tripadvisor:
    - abbr:
      href: https://www.tripadvisor.com
      icon: https://play-lh.googleusercontent.com/EoRcRtru5FLisRd0kCJ5EeTbDQS8oZtLYITsg-58Gv52ryujJtqYwQUYfDDwY3Y9c2U=w240-h480-rw

