---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- search:
    provider: google
    target: _blank
    showSearchSuggestions: true
    focus: true

- datetime:
    locale: ath
    format:
        dateStyle: long
        timeStyle: short

- resources:
    label: CPU
    cpu: true
    units: metric
    refresh: 3000 # optional, in ms

- resources:
    label: RAM
    memory: true
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

- resources:
    label: Disk
    disk: /
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

- resources:
    label: System
    network: true # optional, uses 'default' if true or specify a network interface name
    uptime: true


