---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- logo:
    icon: homepage.png # optional
    href: https://gethomepage.dev/

- datetime:
    locale: ath
    href: https://kimai.desk-portainer.duckdns.org/en/dashboard/
    # href: https://vclock.com/
    format:
        dateStyle: long
        timeStyle: short

- search:
    provider: google
    target: _blank
    showSearchSuggestions: true
    focus: true

- resources:
    label: CPU
    href: https://it-tools.desk-portainer.duckdns.org/
    cpu: true
    units: metric
    refresh: 3000 # optional, in ms

- resources:
    label: RAM
    memory: true
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

# - resources:
#     label: Disk
#     disk: /
#     refresh: 3000 # optional, in ms
#     diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

# - resources:
#     label: System
#     network: true # optional, uses 'default' if true or specify a network interface name
#     uptime: true

- openmeteo:
    label: Her # optional
    latitude: 35.33985933309192
    longitude: 25.13038131721669
    href: https://www.google.com/search?q=weather+in+my+location&client=firefox-b-d&sca_esv=5c59f8709585bb9d&sxsrf=ADLYWIKJLmzCp2rFbHiF7plb4seBmFX_Bg%3A1735435004555&ei=_KJwZ7nMIZP-7_UPiLOqsQc&oq=weather+in+my+lo&gs_lp=Egxnd3Mtd2l6LXNlcnAiEHdlYXRoZXIgaW4gbXkgbG8qAggAMgoQABiABBhGGIACMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMhYQABiABBhGGIACGJcFGIwFGN0E2AEBSOEWUOUDWKwOcAF4AZABAJgBqAGgAdcGqgEDNS4zuAEDyAEA-AEBmAIJoAKGB8ICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIKEAAYgAQYQxiKBcICDxAAGIAEGEMYigUYRhiAAsICGxAAGIAEGEMYigUYRhiAAhiXBRiMBRjdBNgBAcICCxAAGIAEGJECGIoFwgILEAAYgAQYkgMYigXCAggQABiABBjJA5gDAIgGAZAGCboGBggBEAEYE5IHAzQuNaAHvDg&sclient=gws-wiz-serp
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
        maximumFractionDigits: 1


